image: samueldebruyn/debian-git

pipelines:

  default:

    - step:

        script:

          - apt-get update

          - apt-get -qq install git-ftp

          - git ftp push --user 'api@beyahfitness.com' --passwd 'api@beyahfitness.com' 'beyahfitness.com'
