- name: FTP Deploy
  uses: SamKirkland/FTP-Deploy-Action@2.0.0
  with:
    # FTP server name (you may need to specify a port)
    ftp_server: beyahfitness.com
    # FTP account username
    ftp_username: api@beyahfitness.com
    # FTP account password
    ftp_password: api@beyahfitness.com
