- name: git-ftp-action
  uses: sebastianpopp/git-ftp-action@2.1.0
  with:
    # URL
    url: beyahfitness.com
    # FTP login name
    user: api@beyahfitness.com
    # FTP password
    password: api@beyahfitness.com
    # Specifies a local directory to sync from as if it were the git project root path.
    syncroot: # optional, default is .

