name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: git-ftp init
      uses: sebastianpopp/git-ftp-action@releases/v2
      with:
        url: "beyahfitness.com"
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
