on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: beyahfitness.com
        FTP_USERNAME: 'api@beyahfitness.com'
        FTP_PASSWORD: ${{ secrets.FTP_PWD }}
        ARGS: --delete 
        # --delete arg will delete files on the server if you've deleted them in git
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v1.0.0
